version: '3.8'

services:
  lentera-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lentera-backend-container
    ports:
      - "3000:3000"
    env_file:
      - .env
    command: npm run start:prod
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped
